### ISSUE TITLE
start doesn't exist under Linux

### ISSUE THREAD

**Issue by JujuLand** [rjopek/harbour-commander#10]
In place use xdg-open

**Comment by rjopek** [comment]
Hi,

Added link

Linux
- [ Download HC ](https://github.com/rjopek/harbour-commander/releases/download/demo/hc.tar.gz)

Rafał

**Comment by JujuLand** [comment]
Le 24/01/2019 à 18:41, Rafał Jopek a
      écrit :
    
    
      Hi,
      Added link
      Linux
      
        
            Download HC 
      
      Rafał
    
    hc you sent can't be executed on my computer, and, seen with ghex,
    always tried to use start which is a windows tool, not unix ou
    linux.
    But it's not important, the way is just a very little modification
    of the code which then will be always buildable under linux or
    windows:
    
          #if defined( __PLATFORM__WINDOWS )
              hb_run( "start " +
    "https://github.com/rjopek/harbour-commander/issues/new" )
          #else
              hb_run( "xdg-open " +
    "https://github.com/rjopek/harbour-commander/issues/new" )
          #endif
    
    I also added a modification to allow linux users (Ubuntu, Xubuntu,
    Kubuntu, Lubuntu, Ubuntu Mate) to open files other then binary with
    default programs. As terminal name is different between different
    ubuntu flavours, it just need a little test to affect the good
    terminal name.
    
    The terminal is needed to execute shell scripts, elsewhere the
    script should be execute hidden, which is often not desired ...
    Another little problem, is that the scripts needs to have a read
    command at the end to maintain the terminal opened.
    
    In my part of code, I haven't optimized it, in functionkey_f1()
    using a local variable could be prefered to two commandlines.
    
    In prompt, the flavour linux test could be previous to case test, to
    have only one test ... but it should be executed for each case ...
    not too good.
    
    The OS test could be improve, as we can have differences between
    linux and unix ...
    Static procedure prompt()
    
    ...
       LOCAL cNewDrive
    
    #if defined( __PLATFORM__WINDOWS )   //  <<<  Test not
    optimized, PLATFORM_LINUX ?
    #else                                                        //  
    <<<
       LOCAL result:=""
       LOCAL ctuxCmd:="xdg-open "
       LOCAL cTerminal:=""
    #endif
    ...
          CASE K_ENTER
    
             nPos := aPanelSelect[ _nRowBar ] + aPanelSelect[ _nRowNo ]
             IF Empty( aPanelSelect[ _cComdLine ] )
                /* jeżeli stoimy na pliku */
                IF At( "D", aPanelSelect[ _aDirectory ][ nPos ][ F_ATTR
    ] ) == 0
                   #if defined( __PLATFORM__WINDOWS )
                       hb_run( chr(34) + aPanelSelect[ _cCurrentDir ] +
    aPanelSelect[ _aDirectory ][ nPos ][ F_NAME ] + chr(34) )
                   #else
                       if hb_vfExists( "/usr/bin/nautilus" )
                          cTerminal = "gnome-terminal"
                       elseif hb_vfExists( "/usr/bin/thunar" )
                          cTerminal = "xfce4-terminal"
                       elseif hb_vfExists( "/usr/bin/pcmanfm" )
                          cTerminal = "lxterminal"
                       elseif hb_vfExists( "/usr/bin/caja" )
                          cTerminal = "mate-terminal"
                       elseif hb_vfExists( "/usr/bin/dolphin" )
                          cTerminal = "konsole"
                       endif
                       hb_processrun("sh -c 'file "+ aPanelSelect[
    _cCurrentDir ] + aPanelSelect[ _aDirectory ][ nPos ][ F_NAME
    ]+"'"+chr(34),,@result)
                       if at("ELF",result) > 0
                          ctuxCmd=""
                       elseif at("script",result) > 0
                          ctuxCmd=cterminal +" -x "
                       endif
                       hb_run( ctuxCmd + chr(34) + aPanelSelect[
    _cCurrentDir ] + aPanelSelect[ _aDirectory ][ nPos ][ F_NAME ] +
    chr(34) )
                   #endif
                ELSE
                   ChangeDir( aPanelSelect )
                ENDIF
             ELSE
    ....
          CASE K_LDBLCLK
    
             nPos := aPanelSelect[ _nRowBar ] + aPanelSelect[ _nRowNo ]
             /* jeżeli stoimy na pliku */
             IF At( "D", aPanelSelect[ _aDirectory ][ nPos ][ F_ATTR ] )
    == 0
                #if defined( __PLATFORM__WINDOWS )
                    hb_run( chr(34) + aPanelSelect[ _cCurrentDir ] +
    aPanelSelect[ _aDirectory ][ nPos ][ F_NAME ] + chr(34) )
                #else
                    if hb_vfExists( "/usr/bin/nautilus" )
                       cTerminal = "gnome-terminal"
                    elseif hb_vfExists( "/usr/bin/thunar" )
                       cTerminal = "xfce4-terminal"
                    elseif hb_vfExists( "/usr/bin/pcmanfm" )
                       cTerminal = "lxterminal"
                    elseif hb_vfExists( "/usr/bin/caja" )
                       cTerminal = "mate-terminal"
                    elseif hb_vfExists( "/usr/bin/dolphin" )
                       cTerminal = "konsole"
                    endif
                    hb_processrun("sh -c 'file "+ aPanelSelect[
    _cCurrentDir ] + aPanelSelect[ _aDirectory ][ nPos ][ F_NAME
    ]+"'"+chr(34),,@result)
                    if at("ELF",result) > 0
                       ctuxCmd=""
                    elseif at("script",result) > 0
                       ctuxCmd=cterminal +" -x "
                    endif
                    hb_run( ctuxCmd + chr(34) + aPanelSelect[
    _cCurrentDir ] + aPanelSelect[ _aDirectory ][ nPos ][ F_NAME ] +
    chr(34))
                #endif 
             ELSE
                ChangeDir( aPanelSelect )
             ENDIF
    
             EXIT
    
    A+
    -- 
      
      Alain Aupeix
      http://jujuland.pagesperso-orange.fr/
      http://pissobi-lacassagne.pagesperso-orange.fr/
      
      U.buntu 12.04 & Xu.buntu 16.04 | G.ramps 3.4.9-1 |
        H.arbour 3.2.0dev (2018-12-17 11:00) | Hw.Gui (2766)

**Comment by rjopek** [comment]
Hi Alain,

Thank you very much, 
can you make changes to this repository?
I invite you to the project, the project is for all users Harbour. 

or can I make these changes on your behalf?

Rafał

**Comment by JujuLand** [comment]
Le 25/01/2019 à 19:58, Rafał Jopek a
      écrit :
    
    
      Hi Alain,
      Thank you very much,
        can you make changes to this repository?
        I invite you to the project, the project is for all users
        Harbour.
      or can I make these changes on your behalf?
    
    I'm in retirement, and as you know retired are very busy ;)
    
    No, seriously, I don't know about git source managment (except clone
    and pull), and I don't want to make mistake.
    
    But you can simply explain me how to do ... and if I understand,
    maybe I'll do it.
    
    A+
    -- 
      
      Alain Aupeix
      http://jujuland.pagesperso-orange.fr/
      http://pissobi-lacassagne.pagesperso-orange.fr/
      
      U.buntu 12.04 & Xu.buntu 16.04 | G.ramps 3.4.9-1 |
        H.arbour 3.2.0dev (2019-01-25 11:26) | Hw.Gui (2771)

**Comment by rjopek** [comment]
- Accept my github invitation.
- [Installing GitHub Desktop](https://help.github.com/desktop/guides/getting-started-with-github-desktop/installing-github-desktop/)
- Download the repository

For the tests, make small changes.

Easier way:
You can enter these changes directly from the project website
- click hc.prg
- Edit this file
at the bottom of the page
commit changes
write a comment about what you did (It's compulsory)

Rafał

**Comment by rjopek** [comment]
If you have questions, write to my e-mail address

Rafał
