### ISSUE TITLE
Proposal

### ISSUE THREAD

**Issue by jjacenty** [rjopek/harbour-commander#11]
It's a great project, it reminds me of the good old days of Clipper.
...
      CASE 43 /* select a group of files. */         
         for i := 1 to Len( aPanelSelect[ _aDirectory ] )       
            if aPanelSelect[ _aDirectory ][ i ][ F_NAME ] != ".."        
               aPanelSelect[ _aDirectory ][ i ][ F_STATUS ] := .F.         
            endif       
         next   
         EXIT     

      CASE 95 /* Unselect a group of files. */        
         for i := 1 to Len( aPanelSelect[ _aDirectory ] )       
            if aPanelSelect[ _aDirectory ][ i ][ F_NAME ] != ".."  
            aPanelSelect[ _aDirectory ][ i ][ F_STATUS ] := .T.      
            endif       
         next    
         EXIT    
...

I'm afraid that I will not break anything

Jacenty.

**Comment by rjopek** [comment]
Hi, 
Thanks a lot, Your code has been added.

Rafał

**Comment by rjopek** [comment]
Sorry,
Source code provided by Jacenty

Rafał
